/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.CheckingAccount;
import Business.Person;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class CheckingAccountInformationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckingAccountInformationJPanel
     */
    private Person person;
    private JPanel nextJPanel;
    private CheckingAccount checkingAccount = new CheckingAccount();
    
    public CheckingAccountInformationJPanel(Person person, JPanel displayJPanel) {
        initComponents();
        this.person = person;
        nextJPanel = displayJPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bankNameTextField = new javax.swing.JTextField();
        bankRoutingNumberTextField = new javax.swing.JTextField();
        accountNoTextField = new javax.swing.JTextField();
        balanceTextField = new javax.swing.JTextField();
        saveCheckingAccountInformationButton = new javax.swing.JButton();
        goToDriverLicenseInformationButton = new javax.swing.JButton();
        viewCheckingAccountInformationButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Checking Account Information");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Bank Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Bank Routing Number");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Bank Account Number");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Account Balance");

        saveCheckingAccountInformationButton.setBackground(new java.awt.Color(204, 255, 255));
        saveCheckingAccountInformationButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        saveCheckingAccountInformationButton.setText("Save");
        saveCheckingAccountInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCheckingAccountInformationButtonActionPerformed(evt);
            }
        });

        goToDriverLicenseInformationButton.setBackground(new java.awt.Color(204, 255, 255));
        goToDriverLicenseInformationButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        goToDriverLicenseInformationButton.setText("Next");
        goToDriverLicenseInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToDriverLicenseInformationButtonActionPerformed(evt);
            }
        });

        viewCheckingAccountInformationButton.setBackground(new java.awt.Color(204, 255, 255));
        viewCheckingAccountInformationButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        viewCheckingAccountInformationButton.setText("View");
        viewCheckingAccountInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCheckingAccountInformationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(viewCheckingAccountInformationButton))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bankNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(bankRoutingNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(accountNoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(balanceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(goToDriverLicenseInformationButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                .addComponent(saveCheckingAccountInformationButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bankNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bankRoutingNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(accountNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(balanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveCheckingAccountInformationButton)
                    .addComponent(viewCheckingAccountInformationButton))
                .addGap(18, 18, 18)
                .addComponent(goToDriverLicenseInformationButton)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveCheckingAccountInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCheckingAccountInformationButtonActionPerformed
        // TODO add your handling code here:
        checkingAccount.setBankName(bankNameTextField.getText());
        checkingAccount.setBankRoutingNumber(Integer.parseInt(bankRoutingNumberTextField.getText()));
        checkingAccount.setBankAccountNumber(Integer.parseInt(accountNoTextField.getText()));
        checkingAccount.setAccountBalance(Float.parseFloat(balanceTextField.getText()));
        person.setCheckingAccountInfo(checkingAccount);
        JOptionPane.showMessageDialog(null, "Checking Account Information Saved Successfully...");
        clearFields();
    }//GEN-LAST:event_saveCheckingAccountInformationButtonActionPerformed

    private void viewCheckingAccountInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCheckingAccountInformationButtonActionPerformed
        // TODO add your handling code here:
        bankNameTextField.setText(checkingAccount.getBankName());
        bankRoutingNumberTextField.setText(Integer.toString(checkingAccount.getBankRoutingNumber()));
        accountNoTextField.setText(Integer.toString(checkingAccount.getBankAccountNumber()));
        balanceTextField.setText(Float.toString(checkingAccount.getAccountBalance()));
    }//GEN-LAST:event_viewCheckingAccountInformationButtonActionPerformed

    private void goToDriverLicenseInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToDriverLicenseInformationButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) nextJPanel.getLayout();
        nextJPanel.add(new DriverLicenseInformationJPanel(person,nextJPanel));
        layout.next(nextJPanel);
    }//GEN-LAST:event_goToDriverLicenseInformationButtonActionPerformed

     private void clearFields() {
        bankNameTextField.setText(null);
        bankRoutingNumberTextField.setText(null);
        accountNoTextField.setText(null);
        balanceTextField.setText(null);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNoTextField;
    private javax.swing.JTextField balanceTextField;
    private javax.swing.JTextField bankNameTextField;
    private javax.swing.JTextField bankRoutingNumberTextField;
    private javax.swing.JButton goToDriverLicenseInformationButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton saveCheckingAccountInformationButton;
    private javax.swing.JButton viewCheckingAccountInformationButton;
    // End of variables declaration//GEN-END:variables
}
