/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Person;
import Business.Address;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class DemographicInformationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DemographicInformationJPanel
     */
    private Person person;
    private JPanel nextJPanel;
    private Address address;
    SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");

    DemographicInformationJPanel(Person person, JPanel displayJPanel) {
        initComponents();
        this.person = person;
        nextJPanel = displayJPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addInformationJPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        heightTextField = new javax.swing.JTextField();
        weightTextField = new javax.swing.JTextField();
        ssnTextField = new javax.swing.JTextField();
        viewDemographicInformationButton = new javax.swing.JButton();
        saveDemographicInformationButton = new javax.swing.JButton();
        gotoAddressInformationButton = new javax.swing.JButton();
        dateOfBirth = new com.toedter.calendar.JDateChooser();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Add Your Information");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Last Name");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Phone No");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Date of Birth");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Age");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Height");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Weight");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Social Security Number");

        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        viewDemographicInformationButton.setBackground(new java.awt.Color(204, 255, 255));
        viewDemographicInformationButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        viewDemographicInformationButton.setText("View");
        viewDemographicInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDemographicInformationButtonActionPerformed(evt);
            }
        });

        saveDemographicInformationButton.setBackground(new java.awt.Color(204, 255, 255));
        saveDemographicInformationButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        saveDemographicInformationButton.setText("Save");
        saveDemographicInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDemographicInformationButtonActionPerformed(evt);
            }
        });

        gotoAddressInformationButton.setBackground(new java.awt.Color(204, 255, 255));
        gotoAddressInformationButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        gotoAddressInformationButton.setText("Next");
        gotoAddressInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoAddressInformationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addInformationJPanelLayout = new javax.swing.GroupLayout(addInformationJPanel);
        addInformationJPanel.setLayout(addInformationJPanelLayout);
        addInformationJPanelLayout.setHorizontalGroup(
            addInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addInformationJPanelLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel1))
            .addGroup(addInformationJPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(addInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(viewDemographicInformationButton))
                .addGap(84, 84, 84)
                .addGroup(addInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addInformationJPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                        .addComponent(phoneTextField)
                        .addComponent(ageTextField)
                        .addComponent(heightTextField)
                        .addComponent(weightTextField)
                        .addComponent(ssnTextField)
                        .addComponent(saveDemographicInformationButton, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(gotoAddressInformationButton, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(firstNameTextField))))
        );
        addInformationJPanelLayout.setVerticalGroup(
            addInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addInformationJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addInformationJPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(addInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(addInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(weightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(ssnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(addInformationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewDemographicInformationButton)
                    .addComponent(saveDemographicInformationButton))
                .addGap(18, 18, 18)
                .addComponent(gotoAddressInformationButton)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addInformationJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addInformationJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void saveDemographicInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDemographicInformationButtonActionPerformed
        // TODO add your handling code here:
        person.setFirstName(firstNameTextField.getText());
        person.setLastName(lastNameTextField.getText());
        person.setPhoneNo(Long.parseLong(phoneTextField.getText()));
//        person.setDateOfBirth(dobTextField.getText());
        System.out.println(dateOfBirth.getDate());
        person.setDateOfBirth(dateOfBirth.getDate());
        person.setAge(Integer.parseInt(ageTextField.getText()));
        person.setHeight(Float.parseFloat(heightTextField.getText()));
        person.setWeight(Integer.parseInt(weightTextField.getText()));
        person.setSsn(Long.parseLong(ssnTextField.getText()));
        JOptionPane.showMessageDialog(null, "Saved Successfully...");
        clearFields();
    }//GEN-LAST:event_saveDemographicInformationButtonActionPerformed

    private void viewDemographicInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDemographicInformationButtonActionPerformed
        // TODO add your handling code here:
        saveDemographicInformationButton.setVisible(false);
        viewDemographicInformationButton.setVisible(false);
        viewDemographicInformation(person);

    }//GEN-LAST:event_viewDemographicInformationButtonActionPerformed

    private void gotoAddressInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoAddressInformationButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) nextJPanel.getLayout();
        nextJPanel.add(new AddressInformationJPanel(person,nextJPanel));
        layout.next(nextJPanel);

    }//GEN-LAST:event_gotoAddressInformationButtonActionPerformed

    private void viewDemographicInformation(Person person) {
        firstNameTextField.setText(person.getFirstName());
        lastNameTextField.setText(person.getLastName());
        phoneTextField.setText(Long.toString((long) person.getPhoneNo()));
//        dobTextField.setText(person.getDateOfBirth());
//        Date date = person.getDateOfBirth();
//        String date = dateFormat.format(person.getDateOfBirth());
//        System.out.println(date);
        dateOfBirth.setDate(person.getDateOfBirth());
        ageTextField.setText(Integer.toString(person.getAge()));
        heightTextField.setText(Float.toString(person.getHeight()));
        weightTextField.setText(Integer.toString(person.getWeight()));
        ssnTextField.setText(Long.toString((long) person.getSsn()));
    }

    private void clearFields() {
        firstNameTextField.setText(null);
        lastNameTextField.setText(null);
        phoneTextField.setText(null);
//        dobTextField.setText(null);
        dateOfBirth.setDate(null);
        ageTextField.setText(null);
        heightTextField.setText(null);
        weightTextField.setText(null);
        ssnTextField.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addInformationJPanel;
    private javax.swing.JTextField ageTextField;
    private com.toedter.calendar.JDateChooser dateOfBirth;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JButton gotoAddressInformationButton;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JButton saveDemographicInformationButton;
    private javax.swing.JTextField ssnTextField;
    private javax.swing.JButton viewDemographicInformationButton;
    private javax.swing.JTextField weightTextField;
    // End of variables declaration//GEN-END:variables
}
