/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DriverLicense;
import Business.Person;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author DELL
 */
public class DriverLicenseInformationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DriverLicenseInformationJPanel
     */
    private Person person;
    private JPanel nextJPanel;
    private DriverLicense driverLicenseInfo = new DriverLicense(); 
    JFileChooser file = new JFileChooser();
    SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");

    public DriverLicenseInformationJPanel(Person person, JPanel displayJPanel) {
        initComponents();
        this.person = person;
        nextJPanel = displayJPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        licenseNumberTextField = new javax.swing.JTextField();
        saveDriverLicenseInformationButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        bloodTypeTextField = new javax.swing.JTextField();
        viewDriverLinceseInformationButton = new javax.swing.JButton();
        goToMedicalRecordInformationButton = new javax.swing.JButton();
        expiryDate = new com.toedter.calendar.JDateChooser();
        issueDate = new com.toedter.calendar.JDateChooser();

        jToggleButton1.setText("jToggleButton1");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Driver's License Information");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("License Number");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Issue Date");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Expiry Date");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Blood Type");

        saveDriverLicenseInformationButton.setBackground(new java.awt.Color(204, 255, 255));
        saveDriverLicenseInformationButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        saveDriverLicenseInformationButton.setText("Save");
        saveDriverLicenseInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDriverLicenseInformationButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Picture");

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Browse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bloodTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodTypeTextFieldActionPerformed(evt);
            }
        });

        viewDriverLinceseInformationButton.setBackground(new java.awt.Color(204, 255, 255));
        viewDriverLinceseInformationButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        viewDriverLinceseInformationButton.setText("View");
        viewDriverLinceseInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDriverLinceseInformationButtonActionPerformed(evt);
            }
        });

        goToMedicalRecordInformationButton.setBackground(new java.awt.Color(204, 255, 255));
        goToMedicalRecordInformationButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        goToMedicalRecordInformationButton.setText("Next");
        goToMedicalRecordInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToMedicalRecordInformationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(42, 42, 42)
                            .addComponent(licenseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(viewDriverLinceseInformationButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveDriverLicenseInformationButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(goToMedicalRecordInformationButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(issueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(expiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(licenseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(issueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(bloodTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jButton2))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(viewDriverLinceseInformationButton)
                                    .addComponent(saveDriverLicenseInformationButton)))
                            .addComponent(expiryDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(goToMedicalRecordInformationButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

           file.setCurrentDirectory(new File(System.getProperty("user.home")));
           FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images","jpg","gif","png");
           file.addChoosableFileFilter(filter);
           int result = file.showSaveDialog(null);
           //if the user click on save in Jfilechooser
          if(result == JFileChooser.APPROVE_OPTION){
              File selectedFile = file.getSelectedFile();
              String path = selectedFile.getAbsolutePath();
              jLabel7.setIcon(ResizeImage(path));
          }
           //if the user click on save in Jfilechooser
          else if(result == JFileChooser.CANCEL_OPTION){
              System.out.println("No File Selected..");
          }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public ImageIcon ResizeImage(String ImagePath)
    {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(jLabel7.getWidth(), jLabel7.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
      
    
     
    private void saveDriverLicenseInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDriverLicenseInformationButtonActionPerformed
        // TODO add your handling code here:
        driverLicenseInfo.setLicenseNumber(Integer.parseInt(licenseNumberTextField.getText()));
//        driverLicenseInfo.setExpiryDate(expirtyDateTextField.getText());
//        driverLicenseInfo.setIssueDate(issueDateTextField.getText());
        driverLicenseInfo.setBloodType(bloodTypeTextField.getText());
        driverLicenseInfo.setIssueDate(issueDate.getDate());
        
        driverLicenseInfo.setExpiryDate(expiryDate.getDate());
        //Image
        File selectedFile = file.getSelectedFile();
        String path = selectedFile.getAbsolutePath();
        driverLicenseInfo.setImage(path);
       // System.out.println(path);
        person.setDrivingLicenseInfo(driverLicenseInfo);
        JOptionPane.showMessageDialog(null, "Driver's License Information Saved Successfully...");
        clearFields();
    }//GEN-LAST:event_saveDriverLicenseInformationButtonActionPerformed

    private void clearFields() {
        licenseNumberTextField.setText(null);
//        expirtyDateTextField.setText(null);
//        issueDateTextField.setText(null);
        issueDate.setDate(null);
        expiryDate.setDate(null);
        bloodTypeTextField.setText(null);
        jLabel7.setIcon(null);
    }
    
    private void viewDriverLinceseInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDriverLinceseInformationButtonActionPerformed
        // TODO add your handling code here:
        licenseNumberTextField.setText(Integer.toString(driverLicenseInfo.getLicenseNumber()));
//        expirtyDateTextField.setText(driverLicenseInfo.getExpiryDate());
//        issueDateTextField.setText(driverLicenseInfo.getIssueDate());
        issueDate.setDate(driverLicenseInfo.getIssueDate());
        expiryDate.setDate(driverLicenseInfo.getExpiryDate());
        bloodTypeTextField.setText(driverLicenseInfo.getBloodType());
        jLabel7.revalidate();
        String a = driverLicenseInfo.getImage();
        System.out.println(a);
        jLabel7.setIcon(ViewImage(a));
    }//GEN-LAST:event_viewDriverLinceseInformationButtonActionPerformed
    
    private Icon ViewImage(String ImagePath) 
    {
       ImageIcon MyImage = new ImageIcon(ImagePath);
       Image img = MyImage.getImage();
       Image newImg = img.getScaledInstance(jLabel7.getWidth(), jLabel7.getHeight(), Image.SCALE_SMOOTH);
       ImageIcon image = new ImageIcon(newImg);
       return image;
    }
    
    private void bloodTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodTypeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodTypeTextFieldActionPerformed

    private void goToMedicalRecordInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToMedicalRecordInformationButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) nextJPanel.getLayout();
        nextJPanel.add(new MedicalRecordInformationJPanel(person,nextJPanel));
        layout.next(nextJPanel);
    }//GEN-LAST:event_goToMedicalRecordInformationButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloodTypeTextField;
    private com.toedter.calendar.JDateChooser expiryDate;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton goToMedicalRecordInformationButton;
    private com.toedter.calendar.JDateChooser issueDate;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField licenseNumberTextField;
    private javax.swing.JButton saveDriverLicenseInformationButton;
    private javax.swing.JButton viewDriverLinceseInformationButton;
    // End of variables declaration//GEN-END:variables


}
