/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Person;
import Business.SavingAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class SavingAccountInformationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SavingAccountInformationJPanel
     */
    private Person person;
    private JPanel nextJPanel;
    private SavingAccount savingAccount = new SavingAccount();
    
    public SavingAccountInformationJPanel(Person person, JPanel displayJPanel) {
        initComponents();
        this.person = person;
        nextJPanel = displayJPanel;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bankNameTextField = new javax.swing.JTextField();
        bankRoutingNumberTextField = new javax.swing.JTextField();
        accountNoTextField = new javax.swing.JTextField();
        balanceTextField = new javax.swing.JTextField();
        saveSavingAccountInformationButton = new javax.swing.JButton();
        viewSavingAccountInformationButton = new javax.swing.JButton();
        goToCheckingInformationButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Saving Account Information");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Bank Name");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Bank Routing Number");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Bank Account Number");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Account Balance");

        saveSavingAccountInformationButton.setBackground(new java.awt.Color(204, 255, 255));
        saveSavingAccountInformationButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        saveSavingAccountInformationButton.setText("Save");
        saveSavingAccountInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSavingAccountInformationButtonActionPerformed(evt);
            }
        });

        viewSavingAccountInformationButton.setBackground(new java.awt.Color(204, 255, 255));
        viewSavingAccountInformationButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        viewSavingAccountInformationButton.setText("View");
        viewSavingAccountInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSavingAccountInformationButtonActionPerformed(evt);
            }
        });

        goToCheckingInformationButton.setBackground(new java.awt.Color(204, 255, 255));
        goToCheckingInformationButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        goToCheckingInformationButton.setText("Next");
        goToCheckingInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToCheckingInformationButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(viewSavingAccountInformationButton)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(accountNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(balanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankRoutingNumberTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(goToCheckingInformationButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(saveSavingAccountInformationButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bankNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addComponent(bankRoutingNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(accountNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(balanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveSavingAccountInformationButton)
                    .addComponent(viewSavingAccountInformationButton))
                .addGap(18, 18, 18)
                .addComponent(goToCheckingInformationButton)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveSavingAccountInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSavingAccountInformationButtonActionPerformed
        // TODO add your handling code here:
        savingAccount.setBankName(bankNameTextField.getText());
        savingAccount.setBankRoutingNumber(Integer.parseInt(bankRoutingNumberTextField.getText()));
        savingAccount.setBankAccountNumber(Integer.parseInt(accountNoTextField.getText()));
        savingAccount.setAccountBalance(Float.parseFloat(balanceTextField.getText()));
        person.setSavingAccountInfo(savingAccount);
        JOptionPane.showMessageDialog(null, "Saving Account Information Saved Successfully...");
        clearFields();
    }//GEN-LAST:event_saveSavingAccountInformationButtonActionPerformed

    private void goToCheckingInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToCheckingInformationButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) nextJPanel.getLayout();
        nextJPanel.add(new CheckingAccountInformationJPanel(person,nextJPanel));
        layout.next(nextJPanel);
    }//GEN-LAST:event_goToCheckingInformationButtonActionPerformed

    private void viewSavingAccountInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSavingAccountInformationButtonActionPerformed
        // TODO add your handling code here:
        bankNameTextField.setText(savingAccount.getBankName());
        bankRoutingNumberTextField.setText(Integer.toString(savingAccount.getBankRoutingNumber()));
        accountNoTextField.setText(Integer.toString(savingAccount.getBankAccountNumber()));
        balanceTextField.setText(Float.toString(savingAccount.getAccountBalance()));
        
    }//GEN-LAST:event_viewSavingAccountInformationButtonActionPerformed

    private void clearFields() {
        bankNameTextField.setText(null);
        bankRoutingNumberTextField.setText(null);
        accountNoTextField.setText(null);
        balanceTextField.setText(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNoTextField;
    private javax.swing.JTextField balanceTextField;
    private javax.swing.JTextField bankNameTextField;
    private javax.swing.JTextField bankRoutingNumberTextField;
    private javax.swing.JButton goToCheckingInformationButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton saveSavingAccountInformationButton;
    private javax.swing.JButton viewSavingAccountInformationButton;
    // End of variables declaration//GEN-END:variables
}
